import type { LucideIcon } from 'lucide-react';
import { CheckCircle, Eye, Cpu, Scissors } from 'lucide-react';
import type { BlindDetectionResult, PredictionClass } from '../types';
import ConfidenceBar from './ConfidenceBar';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000';

const FORGERY_LABELS: Record<string, string> = {
  spectral_anomaly:     'Spectral 1/f Deviation',
  gan_upsampling:       'GAN Upsampling Artifact',
  noise_inconsistency:  'Noise Inconsistency',
  texture_boundary:     'Texture Boundary Anomaly',
  edge_sharpness:       'Edge/Gradient Anomaly',
  none:                 'None',
};

const CLASS_CONFIG: Record<PredictionClass, {
  label: string;
  color: string;
  bgColor: string;
  borderColor: string;
  icon: LucideIcon;
  desc: string;
}> = {
  REAL: {
    label: 'REAL',
    color: 'text-green-400',
    bgColor: 'bg-green-900/30',
    borderColor: 'border-green-700/50',
    icon: CheckCircle,
    desc: 'Image shows natural characteristics. No manipulation detected.',
  },
  AI_GENERATED: {
    label: 'AI GENERATED',
    color: 'text-red-400',
    bgColor: 'bg-red-900/30',
    borderColor: 'border-red-700/50',
    icon: Cpu,
    desc: 'Image appears to be synthetically generated by a GAN or diffusion model.',
  },
  EDITED: {
    label: 'EDITED / TAMPERED',
    color: 'text-orange-400',
    bgColor: 'bg-orange-900/30',
    borderColor: 'border-orange-700/50',
    icon: Scissors,
    desc: 'Image shows signs of photo editing, splicing, or copy-move manipulation.',
  },
};

interface Props {
  result: BlindDetectionResult;
  imageFile: File;
}

export default function BlindResultPanel({ result, imageFile }: Props) {
  const cfg = CLASS_CONFIG[result.prediction];
  const Icon = cfg.icon;
  const previewUrl = URL.createObjectURL(imageFile);
  const forgeryLabel = FORGERY_LABELS[result.forgery_type] ?? result.forgery_type;
  const isFake = result.prediction !== 'REAL';

  return (
    <div className="space-y-5 animate-in fade-in duration-500">
      {/* Verdict */}
      <div className={`card glow-purple flex items-center gap-4 border ${cfg.borderColor}`}>
        <div className={`w-16 h-16 rounded-2xl flex items-center justify-center flex-shrink-0 ${cfg.bgColor}`}>
          <Icon size={32} className={cfg.color} />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm text-slate-400 uppercase tracking-widest font-medium">Verdict</p>
          <p className={`text-3xl font-bold ${cfg.color}`}>{cfg.label}</p>
          <p className="text-slate-400 text-sm mt-0.5">{cfg.desc}</p>
          <p className="text-slate-400 text-xs mt-1">
            Confidence:{' '}
            <span className="text-slate-200 font-semibold">
              {Math.round(result.confidence * 100)}%
            </span>
            {result.forgery_type !== 'none' && (
              <>
                {' '}· Primary signal:{' '}
                <span className="text-purple-400 font-semibold">{forgeryLabel}</span>
              </>
            )}
          </p>
        </div>
      </div>

      {/* Class Probability Breakdown */}
      <div className="card space-y-3">
        <h3 className="font-semibold text-slate-200 text-sm uppercase tracking-wider">
          Class Probabilities
        </h3>
        <ConfidenceBar
          label="Real"
          value={result.class_probabilities.REAL}
          color="green"
        />
        <ConfidenceBar
          label="AI Generated"
          value={result.class_probabilities.AI_GENERATED}
          color="red"
        />
        <ConfidenceBar
          label="Edited / Tampered"
          value={result.class_probabilities.EDITED}
          color="yellow"
        />
      </div>

      {/* Signal Analysis */}
      <div className="card space-y-3">
        <h3 className="font-semibold text-slate-200 flex items-center gap-2">
          <Eye size={16} className="text-purple-400" /> Signal Analysis
        </h3>
        <ConfidenceBar
          label="Spectral Decay (1/f deviation)"
          value={result.analysis.fft_score}
          color="blue"
        />
        <ConfidenceBar
          label="GAN Periodic Artifacts"
          value={result.analysis.gan_score}
          color="red"
        />
        <ConfidenceBar
          label="Noise Inconsistency"
          value={result.analysis.noise_score}
          color="yellow"
        />
        <ConfidenceBar
          label="Texture Uniformity"
          value={result.analysis.texture_score}
          color="purple"
        />
        <ConfidenceBar
          label="Edge / CNN Proxy"
          value={result.analysis.cnn_score}
          color="green"
        />
      </div>

      {/* Image + Heatmap */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="card space-y-3">
          <p className="text-sm font-medium text-slate-400">Uploaded Image</p>
          <img
            src={previewUrl}
            alt="uploaded"
            className="w-full rounded-xl object-contain max-h-64"
          />
        </div>

        {result.heatmap_url ? (
          <div className="card space-y-3">
            <p className="text-sm font-medium text-slate-400">Anomaly Heatmap</p>
            <img
              src={`${API_BASE}${result.heatmap_url}`}
              alt="heatmap"
              className="w-full rounded-xl object-contain max-h-64"
            />
          </div>
        ) : (
          <div className="card flex items-center justify-center text-slate-600 text-sm h-full min-h-32 border-dashed">
            {isFake ? 'Heatmap generation failed' : 'No heatmap (image classified as real)'}
          </div>
        )}
      </div>
    </div>
  );
}
